export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const ORDER_INIT = "ORDER_INIT";
export const ORDER_BURGER_PENDING = "ORDER_BURGER_PENDING";
export const ORDER_BURGER_SUCCESS = "ORDER_BURGER_SUCCESS";
export const ORDER_BURGER_FAILED = "ORDER_BURGER_FAILED";

export const GET_ORDERS_PENDING = "GET_ORDERS_PENDING";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";
